frequency: 50
sensor_timeout: 0.1
two_d_mode: true
publish_tf: false
transform_time_offset: 0.0
transform_timeout: 0.0
print_diagnostics: true

debug: true
map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: odom
odom0: /odom
imu0: /imu
odom0_config: [true,  true,  false,
                false, false, false,
                true,  true,  true,
                false, false, false,
                false, false, false]
imu0_config:  [false, false, false,
              true,  true,  true,
              false, false, false,
              true,  true,  true,
              true,  true,  true]
odom0_differential: false
imu0_differential: false
odom0_relative: false
imu0_relative: false
