name: build packages CI

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CI: false
      ROS_DISTRO: noetic
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Setup Ros env
      uses: ros-tooling/setup-ros@0.7.0
      with:
        required-ros-distributions: ${{ env.ROS_DISTRO }}

    - name: Install ROS dependencies
      run: |
        sudo apt-get update
        sudo rm /etc/ros/rosdep/sources.list.d/20-default.list
        sudo rosdep init
        rosdep update
        rosdep install --from-paths src --ignore-src -r -y

    - name: Install other dependencies
      run: |
        sudo apt-get install ros-noetic-gazebo-ros-pkgs
        sudo apt-get install ros-noetic-rviz ros-noetic-controller-manager ros-noetic-gazebo-ros ros-noetic-robot-state-publisher ros-noetic-joint-state-publisher-gui

    - name: build and test ROS 1
      uses: ros-tooling/action-ros-ci@v0.2
      with:
        package-name: kiwi_drive kiwi_control kiwi_path kiwi_teleop teleop_keyboard_omni3
        target-ros1-distro: ${{ env.ROS_DISTRO }}