name: build packages CI

on:
    push:
        branches: ['master']

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Ros env
      uses: ros-tooling/setup-ros@0.7.0
      with:
        ros-version: 'noetic'
    - name: Build ROS workspace
      run: |
        catkin build